services:
  # Web Service (FastAPI Application)
  - type: web
    name: calculator-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.database_init && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: calculator-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://calculator-app.onrender.com
    healthCheckPath: /health

  # PostgreSQL Database
  - type: pserv
    name: calculator-db
    env: postgres
    plan: starter
    databases:
      - name: fastapi_db
        user: postgres
